#!/usr/bin/env python3
"""Regenerate _data/papers.js (the data the index.html page reads) from _data/library.json.

Run this after you drop a PDF into a category folder (use the file name shown in the
paper's panel / in _data/missing_pdfs.md) so the index links to it:

    python3 papers/_tools/build_index.py
"""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
lib = json.load(open(os.path.join(ROOT, '_data', 'library.json')))
have = 0
for p in lib['papers']:
    rel = p['pdf_expected']
    p['pdf'] = rel if os.path.exists(os.path.join(ROOT, rel)) else None
    have += bool(p['pdf'])
with open(os.path.join(ROOT, '_data', 'papers.js'), 'w') as f:
    f.write('// generated by _tools/build_index.py - do not edit by hand\nwindow.LIB = ')
    json.dump(lib, f, ensure_ascii=False)
    f.write(';\n')
missing = [p for p in lib['papers'] if not p['pdf']]
with open(os.path.join(ROOT, '_data', 'missing_pdfs.md'), 'w') as f:
    f.write('# Papers without a local PDF\n\nThese are paywalled (mostly IEEE Xplore / ACM DL) and no legitimate open copy was found.\n'
            'Download them through your institution and save each one at the path shown, then run `python3 _tools/build_index.py`.\n\n')
    f.write('| Year | Paper | Venue | DOI | Save as |\n|---|---|---|---|---|\n')
    for p in sorted(missing, key=lambda p: (p['pdf_expected'])):
        doi = p.get('doi') or ''
        f.write(f"| {p.get('year','')} | {p.get('short','')}: {p['title'].replace('|','/')} | {p.get('venue_short','')} | {('['+doi.replace('https://doi.org/','')+']('+doi+')') if doi else ''} | `{p['pdf_expected']}` |\n")
print(f'{len(lib["papers"])} papers, {have} with local PDFs, {len(missing)} missing -> _data/missing_pdfs.md')
