#!/usr/bin/env python3
"""Regenerate _data/papers.js (the data index.html reads), _data/missing_pdfs.md and each folder's README.md
from _data/library.json.

Run this after you drop a PDF into a category folder (use the file name shown in the
paper's panel / in _data/missing_pdfs.md) so the index links to it:

    python3 papers/_tools/build_index.py
"""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
lib = json.load(open(os.path.join(ROOT, '_data', 'library.json')))
have = 0
for p in lib['papers']:
    rel = p['pdf_expected']
    p['pdf'] = rel if os.path.exists(os.path.join(ROOT, rel)) else None
    have += bool(p['pdf'])
# ---- missing-PDF table, ranked by importance & relevance ----
import math
nin = {}
for e in lib['edges']:
    nin[e['t']] = nin.get(e['t'], 0) + 1
CAT_W = {'11': 5, '04': 4, '02': 3.5, '05': 3.5, '01': 3, '03': 3, '07': 3, '06': 2.5, '08': 2.5, '09': 2, '10': 1.5}
CAT_WHY = {'11': 'SLMs on analog/NVM IMC', '04': 'transformer/attention CIM', '02': 'measured silicon', '05': 'model-to-crossbar mapping',
           '01': 'foundational survey', '03': 'core crossbar architecture', '07': 'hardware-aware training', '06': 'non-idealities',
           '08': 'simulator/benchmark', '09': 'ADC/quantization', '10': 'analog training'}
def priority(p):
    n = nin.get(p['id'], 0); c = p.get('cites_global') or 0; y = p.get('year') or 0
    sc = CAT_W.get(p['cat'], 2) + (2 if p.get('slm') else 0) + (2.5 if p.get('seed') else 0) + 1.3 * math.log1p(n) \
         + 0.7 * math.log10(1 + c) + (1 if y >= 2024 else 0.5 if y >= 2021 else 0) + (0.6 if p.get('evidence') == 'measured-silicon' else 0)
    why = [CAT_WHY.get(p['cat'], '')]
    if p.get('slm') and p['cat'] != '11': why.append('runs language models')
    if p.get('seed'): why.append('in original review')
    if n >= 3: why.append(f'cited {n}× in collection')
    if c >= 150: why.append(f'{c} citations overall')
    if p.get('evidence') == 'measured-silicon' and p['cat'] != '02': why.append('measured silicon')
    if y >= 2025: why.append(str(y))
    return sc, ', '.join(w for w in why if w)
missing = sorted([p for p in lib['papers'] if not p['pdf']], key=lambda p: -priority(p)[0])
with open(os.path.join(ROOT, '_data', 'missing_pdfs.md'), 'w') as f:
    f.write('# Papers without a local PDF, ranked by importance and relevance\n\n'
            'Paywalled (mostly IEEE Xplore / ACM DL) with no legitimate open copy found. Download them through your institution, '
            'save each at the path shown, then run `python3 _tools/build_index.py`. This table re-sorts itself each run.\n\n'
            'Ranking = topical relevance (SLMs on analog/NVM IMC first, then transformer CIM, measured chips, mapping, …) '
            '+ language-model focus + cited by the original review + how often papers in this collection cite it '
            '+ overall citations + recency + measured silicon. Tier 1 = top 25, Tier 2 = next 35, Tier 3 = the rest.\n\n')
    f.write('| # | Tier | Year | Paper | Venue | Why it matters | DOI | Save as |\n|---|---|---|---|---|---|---|---|\n')
    for i, p in enumerate(missing, 1):
        sc, why = priority(p); tier = 1 if i <= 25 else 2 if i <= 60 else 3
        doi = p.get('doi') or ''
        f.write(f"| {i} | {tier} | {p.get('year','')} | **{(p.get('short') or '').replace('|','/')}**: {p['title'].replace('|','/')} | {p.get('venue_short','')} | {why} | "
                f"{('['+doi.replace('https://doi.org/','')+']('+doi+')') if doi else ''} | `{p['pdf_expected']}` |\n")
    for p in lib['papers']:
        p['priority'] = round(priority(p)[0], 2)
cats = {c['id']: c for c in lib['categories']}
for cid, c in cats.items():
    ps = sorted([p for p in lib['papers'] if p['cat'] == cid], key=lambda p: (-(p.get('year') or 0), p['title']))
    n_pdf = sum(1 for p in ps if p['pdf'])
    with open(os.path.join(ROOT, c['dir'], 'README.md'), 'w') as f:
        f.write(f"# {cid} · {c['name']}\n\n{c['desc']}\n\n{len(ps)} papers, {n_pdf} with a local PDF. "
                "Open `../index.html` for summaries, claims, remarks and citation contexts.\n\n"
                "| Year | Paper | Venue | TL;DR | File |\n|---|---|---|---|---|\n")
        for p in ps:
            fn = os.path.basename(p['pdf_expected']); doi = p.get('doi') or ''
            link = f"[{fn}]({fn})" if p['pdf'] else (f"[DOI]({doi}) (no local PDF)" if doi else '')
            f.write(f"| {p.get('year','')} | **{p.get('short') or ''}** {p['title'].replace('|','/')} | "
                    f"{p.get('venue_short') or p.get('venue','')} | {(p.get('tldr') or '').replace('|','/')} | {link} |\n")
        notes = os.path.join(ROOT, '_data', 'folder_notes', c['dir'] + '.md')
        if os.path.exists(notes):
            f.write('\n' + open(notes).read())
with open(os.path.join(ROOT, '_data', 'papers.js'), 'w') as f:
    f.write('// generated by _tools/build_index.py - do not edit by hand\nwindow.LIB = ')
    json.dump(lib, f, ensure_ascii=False)
    f.write(';\n')
print(f'{len(lib["papers"])} papers, {have} with local PDFs, {len(missing)} missing -> _data/missing_pdfs.md')
